package model;
// Generated 11-sep-2015 18:56:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Conexionentrantes generated by hbm2java
 */
public class Conexionentrantes  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private String direccionIp;

    public Conexionentrantes() {
    }

    public Conexionentrantes(String direccionIp) 
    {
       this.direccionIp = direccionIp;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getDireccionIp() {
        return this.direccionIp;
    }
    
    public void setDireccionIp(String direccionIp) {
        this.direccionIp = direccionIp;
    }




}


