package model;
// Generated 11-sep-2015 18:56:52 by Hibernate Tools 4.3.1



/**
 * Jugadasrecibidas generated by hbm2java
 */
public class Jugadasrecibidas  implements java.io.Serializable {


     private Integer id;
     private int fkConexionEntrante;
     private String numeroJugado;
     private int dineroApostado;

    public Jugadasrecibidas() {
    }

    public Jugadasrecibidas(int fkConexionEntrante, String numeroJugado, int dineroApostado) {
       this.fkConexionEntrante = fkConexionEntrante;
       this.numeroJugado = numeroJugado;
       this.dineroApostado = dineroApostado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFkConexionEntrante() {
        return this.fkConexionEntrante;
    }
    
    public void setFkConexionEntrante(int fkConexionEntrante) {
        this.fkConexionEntrante = fkConexionEntrante;
    }
    public String getNumeroJugado() {
        return this.numeroJugado;
    }
    
    public void setNumeroJugado(String numeroJugado) {
        this.numeroJugado = numeroJugado;
    }
    public int getDineroApostado() {
        return this.dineroApostado;
    }
    
    public void setDineroApostado(int dineroApostado) {
        this.dineroApostado = dineroApostado;
    }




}


