package model;
// Generated 11-sep-2015 18:56:52 by Hibernate Tools 4.3.1



/**
 * Numerosgenerados generated by hbm2java
 */
public class Numerosgenerados  implements java.io.Serializable {


     private Integer id;
     private int fkConexionEntrante;
     private String numeroGeneradoPropiamente;
     private int orden;

    public Numerosgenerados() {
    }

    public Numerosgenerados(int fkConexionEntrante, String numeroGeneradoPropiamente, int orden) {
       this.fkConexionEntrante = fkConexionEntrante;
       this.numeroGeneradoPropiamente = numeroGeneradoPropiamente;
       this.orden = orden;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getFkConexionEntrante() {
        return this.fkConexionEntrante;
    }
    
    public void setFkConexionEntrante(int fkConexionEntrante) {
        this.fkConexionEntrante = fkConexionEntrante;
    }
    public String getNumeroGeneradoPropiamente() {
        return this.numeroGeneradoPropiamente;
    }
    
    public void setNumeroGeneradoPropiamente(String numeroGeneradoPropiamente) {
        this.numeroGeneradoPropiamente = numeroGeneradoPropiamente;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }




}


