package model;
// Generated 11-sep-2015 18:56:52 by Hibernate Tools 4.3.1



/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer id;
     private String serial;
     private float saldo;

    public Tarjeta() {
    }

    public Tarjeta(String serial, float saldo) {
       this.serial = serial;
       this.saldo = saldo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }
    public float getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(float saldo) {
        this.saldo = saldo;
    }

    @Override
    public String toString() {
        return "Tarjeta{" + "id=" + id + ", serial=" + serial + ", saldo=" + saldo + '}';
    }
    



}


